# Generated by Django 4.1 on 2024-09-06 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0003_college_industryorganization_individual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegestudent',
            name='college',
            field=models.TextField(),
        ),
    ]
