# Generated by Django 4.1 on 2024-09-21 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0004_alter_collegestudent_college'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('number_of_trees', models.IntegerField(choices=[(1, '1000'), (5, '5000'), (10, '10000')])),
            ],
        ),
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number_of_trees', models.IntegerField()),
                ('date_planted', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='tree_photos/')),
                ('video', models.FileField(blank=True, null=True, upload_to='tree_videos/')),
                ('is_active', models.BooleanField(default=True)),
                ('tree_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tree.treeplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
