# Generated by Django 4.1 on 2024-09-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0005_treeplan_tree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treeplan',
            name='number_of_trees',
            field=models.IntegerField(choices=[(1, '1'), (2, '5'), (3, '10')]),
        ),
    ]
